server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/newsletter_db
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    addresses: ${RABBITMQ_ADDRESSES}
    queue:
      verification:
        name: subscriber.verification.queue
      notification:
        name: news.notification.queue

news:
  api:
    key: ${NEWS_API_KEY}
    base-url: https://gnews.io/api/v4/top-headlines